w4d2/Cats/config/routes.rb
Rails.application.routes.draw do

  resources :cats
  resources :cat_rental_requests, except: [:show]

end

w4d2/Cats/app/models/cat.rb
class Cat < ActiveRecord::Base
  COLOR = ["black", "white", "brown", "orange"]

  validates :birth_date, :name, presence: true
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not valid" }
  validates :color, inclusion: { in: COLOR,
    message: "%{value} is not a valid color" }


  has_many(
    :cat_rental_requests,
    :foreign_key => :cat_id,
    :primary_key => :id,
    :class_name => "CatRentalRequest",
    :dependent => :destroy
  )
end

w4d2/Cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUS = ["PENDING", "APPROVED", "DENIED"]

  after_initialize do |crr|
    crr.status ||= "PENDING"
  end
  validates :cat_id, :start_date, :end_date, :presence => true
  validate :sensible_date
  validates :status, inclusion: {in: STATUS}
  validate :overlapping_approved_requests


  belongs_to(
    :cat,
    :foreign_key => :cat_id,
    :primary_key => :id,
    :class_name => "Cat"
  )

  def approve!
    self.status = "APPROVED" if self.status = "PENDING"
    self.save!
    deny_overlapping_pending_requests
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == "PENDING"
  end

  private

  def overlapping_requests(requests)
    requests.all? do |request|
      !overlaps?(request)
    end
  end

  def overlaps?(other)
    (start_date - other.end_date) * (other.start_date - end_date) >= 0
  end

  def overlapping_approved_requests
    results = CatRentalRequest.where cat_id:cat_id, status:"APPROVED"
    return true if results.length <= 1
    if overlapping_requests(results)
      errors[:bad_request] << "It overlaps with someone else's request"
    end
  end

  def deny_overlapping_pending_requests
    results = CatRentalRequest.where cat_id:cat_id, status:"PENDING"
    results.each do |result|
      result.deny! if overlaps?(result)
    end
  end

  def sensible_date
    if (start_date > end_date) || (start_date >= Time.now.to_date)
      errors[:bad_dates] << "Your dates don't make sense"
    end
  end
end

w4d2/Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

w4d2/Cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    render :new
  end

  def create
    @request = CatRentalRequest.new(crr_params)
    if @request.save
      redirect_to cat_path(params[:cat_rental_request][:cat_id])
    else
      render(
        json: @request.errors.full_messages, status: 422
      )
    end
  end

  def update
    # byebug
    @crr = CatRentalRequest.find(params[:id])
    if params[:status] == "approve"
      @crr.approve!
    elsif params[:status] == "deny"
      @crr.deny!
    end
    redirect_to cat_path(@crr.cat_id)
  end

  private

  def crr_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id)
  end

end

w4d2/Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def index
    @cats = Cat.all
    render :index
  end

  def new
    @cat = Cat.new(:birth_date => Time.now, :color => nil, :name => "", :sex => nil, :description => nil)
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_path(@cat.id)
    else
      render(
        json: @cat.errors.full_messages, status: 422
      )
    end
  end

  def create
    @new_cat = Cat.new(cat_params)
    if @new_cat.save
      redirect_to cats_path
    else
      render(
        json: @new_cat.errors.full_messages, status: 422
      )
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

w4d2/Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d2/Cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

w4d2/Cats/app/helpers/cats_helper.rb
module CatsHelper
end

w4d2/Cats/app/views/cats/_form.html.erb
<% if @cat.persisted? %>
  <form action="<%= cat_path(@cat.id) %>" method="post">
    <input type="hidden" name="_method" value="patch">
<% else %>
  <form action="<%= cats_url %>" method="post">
<% end %>

  <label for="birthdate">Birthdate</label>
  <input type="date" name="cat[birth_date]" id="birthdate" value="<%= @cat.birth_date.to_date %>">
  <br>
  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <% if @cat.color.nil? %>
    <option value="" selected="selected"></option>
    <% end %>
    <% Cat::COLOR.each do |color| %>
      <option value=<%= color %>
        <%= selected="selected" if @cat.color == color %>>
        <%= color.capitalize %> </option>
    <% end %>
  </select>
  <br>
  <label for="name">Name</label>
  <input type="text" name="cat[name]" id="name" value="<%= @cat.name %>">
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%=checked="checked" if @cat.sex == "F" %> >
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%=checked="checked" if @cat.sex == "M" %> >
  <label for="cat_sex_male">Male</label>
  <br>
  <label for="desc">Description</label>
  <input type="textarea" name="cat[description]" id="desc" value="<%= @cat.description %>">
  <br>
  <% if @cat.persisted? %>
    <input type="submit" value="Update cat">
  <% else %>
    <input type="submit" value="Create cat">
  <% end %>

</form>

w4d2/Cats/app/views/cats/edit.html.erb
<!DOCTYPE html>
<html>
<body>
  <h1> Edit a cat. </h1>
  <!-- <form action="<%= cat_path(@cat.id) %>" method="post">
    <input type="hidden" name="_method" value="patch"> -->
    <%= render "form" %>
  <!-- </form> -->
</body>
</html>

w4d2/Cats/app/views/cats/index.html.erb
<!DOCTYPE html>
<html>
<body>
  <h1> Cats </h1>
  <ul>
    <% @cats.each do |cat| %>
    <li>
      <%= link_to cat.name, cat_path(cat.id) %>
    </li>
    <% end %>
  </ul>
  <br>
  <%= link_to "New Cat", new_cat_path %>
  <br>
  <br>
  <%= link_to "Request a cat", new_cat_rental_request_path %>
</body>
</html>

w4d2/Cats/app/views/cats/new.html.erb
<!DOCTYPE html>
<html>
<body>
  <h1> Make a new cat. </h1>
  <%= render "form" %>
</body>
</html>

w4d2/Cats/app/views/cats/show.html.erb
<!DOCTYPE html>
<html>
<body>
<h1>About this cat:</h1>
  <table>
    <tr>
      <th>Birth date</th>
      <th>Color</th>
      <th>Name</th>
      <th>Sex</th>
      <th>Description</th>
    </tr>
    <tr>
      <td><%= @cat.birth_date %></td>
      <td><%= @cat.color %></td>
      <td><%= @cat.name %></td>
      <td><%= @cat.sex %></td>
      <td><%= @cat.description || "No description" %></td>
    </tr>
  </table>
  <br>
  <br>
  <h2>Rental Requests</h2>
  <table>
  <% CatRentalRequest.where(cat_id: @cat.id).order(:start_date).each do |crr| %>
    <tr>
      <% unless crr.status == "DENIED" %>
        <td> <%= "From #{crr.start_date} to #{crr.end_date}" %> </td>
        <% if crr.pending? %>
          <td> <%= button_to "Approve", "#{cat_rental_requests_url}/#{crr.id}", method: :patch, params: {status: :approve} %> </td>
          <td> <%= button_to "Deny", "#{cat_rental_requests_url}/#{crr.id}", method: :patch, params: {status: :deny} %> </td>
        <% end %>
      <% end %>
  </tr>
  <% end %>
  </table>

  <br>
  <br>
  <%= link_to "All Cats", cats_url %>
</body>
</html>